sudo: false
language: python
dist: xenial

python:
  - "2.7"
  - "3.7"

env:
  - TORCH_VERSION=1.0.1
  - TORCH_VERSION=0.4.1

cache:
  apt: true
  directories:
    - $HOME/.cache/pip

install:

  - wget http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - hash -r
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install -c pytorch pytorch-cpu=$TORCH_VERSION numpy scipy pytest cython

  # install package
  - cd pytorch
  - pip install .

script:
  - mkdir empty_dir
  - pytest pytest -vs --pyargs torchsparseattn
  - cd .. 
